"""Ported verbatim from src/data/clubs.ts. Do not edit by hand — regenerate from source
if the app's club list ever changes."""

CLUB_LEAGUES = {
    "ac-milan": "serie-a",
    "alaves": "la-liga",
    "arsenal": "premier-league",
    "as-monaco": "ligue-1",
    "as-roma": "serie-a",
    "aston-villa": "premier-league",
    "atalanta": "serie-a",
    "athletic-bilbao": "la-liga",
    "atletico-madrid": "la-liga",
    "barcelona": "la-liga",
    "bayer-leverkusen": "bundesliga",
    "bayern-munich": "bundesliga",
    "bologna": "serie-a",
    "borussia-dortmund": "bundesliga",
    "bournemouth": "premier-league",
    "brentford": "premier-league",
    "brighton": "premier-league",
    "celta-vigo": "la-liga",
    "chelsea": "premier-league",
    "como": "serie-a",
    "crystal-palace": "premier-league",
    "eintracht-frankfurt": "bundesliga",
    "everton": "premier-league",
    "fiorentina": "serie-a",
    "fulham": "premier-league",
    "genoa": "serie-a",
    "getafe": "la-liga",
    "hull-city": "premier-league",
    "inter": "serie-a",
    "ipswich-town": "premier-league",
    "juventus": "serie-a",
    "lazio": "serie-a",
    "leeds-united": "premier-league",
    "lille": "ligue-1",
    "liverpool": "premier-league",
    "lyon": "ligue-1",
    "manchester-city": "premier-league",
    "manchester-united": "premier-league",
    "marseille": "ligue-1",
    "monza": "serie-a",
    "napoli": "serie-a",
    "newcastle-united": "premier-league",
    "nottingham-forest": "premier-league",
    "ogc-nice": "ligue-1",
    "osasuna": "la-liga",
    "paris-fc": "ligue-1",
    "psg": "ligue-1",
    "racing-santander": "la-liga",
    "rayo-vallecano": "la-liga",
    "rb-leipzig": "bundesliga",
    "rc-lens": "ligue-1",
    "real-betis": "la-liga",
    "real-madrid": "la-liga",
    "real-sociedad": "la-liga",
    "rennes": "ligue-1",
    "sassuolo": "serie-a",
    "sc-freiburg": "bundesliga",
    "schalke-04": "bundesliga",
    "sevilla": "la-liga",
    "strasbourg": "ligue-1",
    "sunderland": "premier-league",
    "torino": "serie-a",
    "tottenham": "premier-league",
    "tsg-hoffenheim": "bundesliga",
    "udinese": "serie-a",
    "valencia": "la-liga",
    "venezia": "serie-a",
    "vfb-stuttgart": "bundesliga",
    "villarreal": "la-liga",
}


def league_of_club(club_slug):
    return CLUB_LEAGUES.get(club_slug)


# Spin the Wheel's club-mode cap: top 15 clubs by player count (wheelEngine.ts's
# TOP_WHEEL_CLUBS), cross-checked against the slugs above.
TOP_WHEEL_CLUBS = [
    "real-madrid",
    "arsenal",
    "barcelona",
    "juventus",
    "tottenham",
    "chelsea",
    "liverpool",
    "atletico-madrid",
    "bayern-munich",
    "manchester-united",
    "psg",
    "aston-villa",
    "napoli",
    "manchester-city",
    "inter",
]
assert all(slug in CLUB_LEAGUES for slug in TOP_WHEEL_CLUBS)
assert len(TOP_WHEEL_CLUBS) == 15
